import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar"; // Add this import
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap');
        </style>
      </head>
      <body className={`antialiased`}>
        <Navbar /> {/* Add the Navbar component here */}
        <main className="pt-16"> {/* Add padding-top to prevent content from hiding under navbar */}
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
